"""
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in th eFibonacci sequence whose values do not exceed four million, find the sum of th even-valued terms
"""

from functions_file import projecteuler_fibonacci
from functions_file import even_valued_term

sum = 0
#no puedes hacer un for porque no sabes cual (i) es el último que necesitas
i = 1
while(projecteuler_fibonacci(i) < 4000000):
	if(even_valued_term(projecteuler_fibonacci(i))): sum += projecteuler_fibonacci(i)
	i += 1
print(sum)

#sum = 4613732